const dbConfig = require("../config/db.config.js");
const mongoose = require("mongoose");
mongoose.Promise = global.Promise;
const db = {};
db.mongoose = mongoose;
mongoose.set('useFindAndModify', false);
db.url = dbConfig.url;
db.livro = require("./livro.model.js")(mongoose);
db.usuario = require("./usuario.model.js")(mongoose);
module.exports = db;